### ISSUE TITLE
Trouble copying to clipboard 

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#1]
When the card is hovering, I can't really do Ctrl+C on words or phrases.

Steps to reproduce:

* be me
* go to https://www.japanesepod101.com/japanese-phrases/10232017?meaning
* select first phrase in Japanese, watch as the helpful translation comes up
* try to copy the text in the page, only to fail

Seems to work only if you move the mouse away.

**Comment by picsi** [comment]
On further inspection it seems it doesn't let me type anything either

**Comment by birtles** [comment]
Oh nice report! Thank you!

I've never encountered this because I only turn on the tool for a short time and then turn it off again. I'll try to work up a fix for this later today.

**Comment by birtles** [comment]
Version 0.0.5 is out now and should fix this.

There are still other bugs when dealing with text boxes (especially with scroll bars) but I hope to fix them in the coming days.
