### ISSUE TITLE
Option to delay popup to appear

### ISSUE THREAD

**Issue by Lebon14** [birtles/rikaichamp#10]
Hi.

Thank you so so so much for bringing this to FF 57! Without this addon, I was upgrading from FF 56 at all.

Anyway, when I move my screen around and there's lots of Japanese, the popup appears INSTANTLY. So, even if pass even one frame over a character with my mouse, it's going to trigger and popup a box. It's kind of annoying. So, I was wondering you could implement some kind of delay (from, say, none to 500 ms) so that when I just moving my mouse around I'm not bothered by Rikaichamp popups for absolutely nothing.

Cheers and thanks for the hard work.

**Comment by birtles** [comment]
Not at all, you are very welcome! Thank you for using rikaichamp!

I was thinking of making rikaichamp detect the mouse velocity and only show the pop-up if the mouse is moving slowly or is stationary. Would that work for you?

**Comment by Lebon14** [comment]
I'd have to see for myself, because, even when I move my mouse very fast over characters, the popup shows up. So yeah, that could help too.

**Comment by birtles** [comment]
I'll give it a try in the next release and if it doesn't work, I'll add the delay option.

**Comment by Lebon14** [comment]
Awesome! Thanks for the hard work!

**Comment by OskarPeredo** [comment]
@birtles I think a mix of the 2 is needed, since a fast mouse movement would disable the popup to be seen but once the mouse isn't moving it should show the popup to whatever word it is currently hovering at.

**Comment by birtles** [comment]
Yeah, I'll give it a try -- I assume the mouse won't normally stop on a dime so you'd get at least one `mousemove` event where the velocity is low enough to display the pop-up.

**Comment by redshoulder** [comment]
Yes, a delay would be very helpful, it wasn't needed before because rikaichan was very slow.

**Comment by Lebon14** [comment]
With 0.10 here (where are the release notes btw?), it didn't improve at all... For testing, I was moving my mouse cursor over a tweet. You could see that the numerous popups. And it wasn't slow either; it was a very fast waggling over the text. :\

And, yes, in the past, Rikaichan was so slow that such option wasn't needed.

**Comment by birtles** [comment]
The release notes are:
* [changelog.md](https://github.com/birtles/rikaichamp/blob/master/changelog.md), or
* On (addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/rikaichamp/versions/)

And as you notice I haven't gotten to this issue yet. It's number 2 on my list of things to-do though (number 1 being fixing some problems I noticed when using Gmail's pop-up compose window).

I'll update this issue when I make some change.

**Comment by birtles** [comment]
I've tweaked this in version 0.0.11 so please give it a try. It's not perfect -- I set the speed tolerance for hiding the popup pretty high since otherwise the tooltip over images would rarely show (since you often do just mouse over the image and then stop) -- but let me know if it helps.

Also, it doesn't help with scrolling since I mistakenly used `clientX` and `clientY` instead of `pageX` and `pageY`. I'll fix that in the next release though.

**Comment by Lebon14** [comment]
Perfect!! Works perfect!

**Comment by birtles** [comment]
Great! I'll fix the scrolling issue soon but it sounds like I can close this issue for now.
