### ISSUE TITLE
Popup appears without the mouse being on top of the word.

### ISSUE THREAD

**Issue by OskarPeredo** [birtles/rikaichamp#11]
I've noticed that under my environment:

MacOS High Sierra
Firefox 57

The popup tends to appear even when I'm not on top of any words. It seems to "attach" to the closest word even when it is on the next line. 

You can reproduce this issue easily on this page:

https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E8%AA%9E

There's a 日本語 subtitle on the right side. Just by going inside the cell of the word it's automatically detecting it.

**Comment by birtles** [comment]
Yes, that's deliberate and it comes from rikaikun. It's supposed to make it easier for you to select a word, especially with small fonts since you don't need to carefully position the mouse exactly on top of the starting character of the word.

**Comment by OskarPeredo** [comment]
I see, but I've also noticed it selects word even when they are not on the same line. (I've marked the mouse position with a red circle and an arrow)
<img width="1279" alt="mouseposition" src="https://user-images.githubusercontent.com/1725561/32823626-3277b8f0-ca21-11e7-9bf4-33962f005fb8.png">

Is there a way to "reduce the effective area" or something similar? since I'm trying to place the mouse where there's nothing so that the popup doesn't show but more often than not it ends up detecting something else.

**Comment by birtles** [comment]
Oh, that's a different case -- I think that's just the result that `caretPositionFromPoint` gives then. We could probably work around that by getting back the character position and checking if it's far away.

**Comment by birtles** [comment]
I started working on this--wrote the tests, got it to pass, everything looked great, but then I tried it on some more representative content and it seems like `getBoundingClientRect()` is too buggy to rely on as a measure of how far the mouse is from the actually selected text. I mean it mostly works, but sometimes (like when using spans) is well-off. I could try using `getBoxQuads` but that doesn't work for a range. I'm not sure what other options I have.

**Comment by birtles** [comment]
I managed to determine that `getBoundingClientRect` is unreliable for SVG content ([bug 1426594](https://bugzilla.mozilla.org/show_bug.cgi?id=1426594)) and vertical text ([bug 1159309](https://bugzilla.mozilla.org/show_bug.cgi?id=1159309)). It would be pretty easy to just skip the check in those two cases but I'm a little concerned that there may be others.

Looking at the [list of getBoundingClientRect bugs](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=getBoundingClientRect&list_id=13940441) most of them seem to be SVG-related and SVG probably doesn't need this extra distance check so maybe it's ok to add.

**Comment by birtles** [comment]
I've created #24 for this, but I'm not entirely sure if I want to merge it or not -- still a bit concerned about false positives and potential performance impact.

**Comment by kikaxa** [comment]
i have tested this patch for some time and have not found yet any false positives.
performance is tiny bit higher when popup is needed and lower otherwise.
the bug seems fixed in all the cases i have seen.

**Comment by birtles** [comment]
Great, thanks for checking that! Ideally I'd like to create a beta/development version of rikaichamp so that interested people can try this out in their daily browsing.

**Comment by kikaxa** [comment]
@birtles ironically, i have stumbled upon (i think) false positive on the first day of release:
http://nec-lavie.jp/products/nm/
for the left-sided ad paragraphs (外出先でも、...)
also seems somewhat related to #27

**Comment by birtles** [comment]
> @birtles ironically, i have stumbled upon (i think) false positive on the first day of release:
> http://nec-lavie.jp/products/nm/
> for the left-sided ad paragraphs (外出先でも、...)
> also seems somewhat related to #27

Yes, that definitely looks like #27 but looking at the source there are no transforms involved. Do you mind filing a separate issue for that?
