### ISSUE TITLE
-tari and -tara inflections

### ISSUE THREAD

**Issue by toasted-nutbread** [birtles/rikaichamp#110]
I was recently updating some inflection data for https://github.com/FooSoft/yomichan/pull/199 and it was noticed that there are some rules which seem to be mixed up. Specifically, some of the -tari and -tara rules seem to be switched. For example, see 往ったら on lines 178 and 182 of: https://github.com/birtles/rikaichamp/blob/1467cf459c974b86889a39993ce469aa289f2ea2/src/deinflect.ts#L178-L182

Maybe because ```DeinflectReason.Tari``` was repeated twice on line 179 and 180, whereas it usually looks like it's alternating between ```DeinflectReason.Tara``` and ```DeinflectReason.Tari```?

Anyway, not clear if this is on purpose or not. If it's a bug, I can create a PR to fix it if you like.

**Comment by birtles** [comment]
Yeah, that definitely looks like a bug!

**Comment by birtles** [comment]
Closed by 6cdd179811a0a0a183353aa9dcbfe69bbf1608e5
