### ISSUE TITLE
Keep on/off state across browser restarts

### ISSUE THREAD

**Issue by Tomalak** [birtles/rikaichamp#12]
Every time I start Firefox, the extension is currently off. 

It should remain in the same state it was when the browser was shut down.

**Comment by birtles** [comment]
That's a good idea. I'll see what I can do.

**Comment by birtles** [comment]
Hmm, that didn't seem to work. I'm not sure why yet.

**Comment by birtles** [comment]
Oh, so it turns out that `local` in the web extensions API is equivalent to `localStorage`, not `sessionStorage`.

**Comment by birtles** [comment]
I guess the extension should just use `sessionStorage`.
