### ISSUE TITLE
Please add support for larest thunderbird

### ISSUE THREAD

**Issue by vimesh-pro** [birtles/rikaichamp#131]
Please add support for larest thunderbird

**Comment by birtles** [comment]
Unfortunately it's not currently possible since Thunderbird does not have the required APIs for running JS on message view or compose view although I have interacting with Thunderbird devs to try to get them added.

Closing as a dupe of #46.

**Comment by vimesh-pro** [comment]
What about TB 68.0?
Is there anything changed?

**Comment by birtles** [comment]
No, it's still not possible even in the latest development versions I'm afraid.
