### ISSUE TITLE
Better scope styles

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#144]
I received the following report that Rikaichamp sometimes picks up the fonts from the page:

![image](https://user-images.githubusercontent.com/1232595/69314740-3c918500-0c78-11ea-8087-bdd1a3b89d41.png)

Unfortunately I cannot reproduce it locally. The issue appears to have occurred on a German Windows system so perhaps it is related to the available fonts.

However, I have been thinking about using shadow DOM for the rikaichamp window so that styles from the content document don't leak into it and we can use simpler CSS selectors. I think that might fix this issue too.

**Comment by birtles** [comment]
Received [another report](https://addons.mozilla.org/en-US/firefox/addon/rikaichamp/reviews/1451106/) that is likely the same cause:
> on www.orangepage.net, the popup window shrinks and turns transparent and thus unreadable

**Comment by Tomalak** [comment]
I can confirm that have the same issue and it _seems_ to be related to serif/sans serif font settings in the browser, and subsequently to which base font the page has picked.
