### ISSUE TITLE
Text wrapping in new kanji popup

### ISSUE THREAD

**Issue by Kala-J** [birtles/rikaichamp#149]
Text from readings/definitions of kanji extends past the border of the window.
<img width="525" alt="rb1" src="https://user-images.githubusercontent.com/47021172/69767304-f3cd5500-11be-11ea-86a4-53f7db9cd01a.png">
<img width="441" alt="rb2" src="https://user-images.githubusercontent.com/47021172/69767305-f3cd5500-11be-11ea-8e75-d2e4a7e00441.png">

**Comment by birtles** [comment]
Oh, interesting. Thanks for the report!

For my testing: 和 seems to reproduce consistently (家 doesn't wrap for me).

**Comment by Kala-J** [comment]
家 doesn't wrap but it should, because the 'r' from "performer" doesn't fit in the window.

**Comment by birtles** [comment]
For me it fits in the window. It looks like we have different fonts:

![image](https://user-images.githubusercontent.com/1232595/69767622-83273800-11c0-11ea-9be8-872d332891be.png)

**Comment by Kala-J** [comment]
The window width seems to change depending on the website, but the text wrapping doesn't account for it. For example, this is 和 on wikipedia:

<img width="389" alt="rb3" src="https://user-images.githubusercontent.com/47021172/69768247-2da05a80-11c3-11ea-863e-f8d701d9bdbe.png">

Also on wikipedia, the entry for '水' wraps far too early since there is clearly space, while on jisho.org it wraps right at the edge.

<img width="379" alt="rb4" src="https://user-images.githubusercontent.com/47021172/69768301-68a28e00-11c3-11ea-8439-c17b586f41ab.png">
<img width="374" alt="rb5" src="https://user-images.githubusercontent.com/47021172/69768302-68a28e00-11c3-11ea-9080-c17360074c35.png">

**Comment by Kala-J** [comment]
When I look at '家' in the comments here on github it looks the same as what you posted, since the width of the popup is different from jisho.org.

**Comment by Kala-J** [comment]
I've also found that the kanji parts radical visual highlight also sometimes extends past the edge of the popup, so it definitely looks like a problem with the width of the window.

(viewed on jisho.org)
<img width="373" alt="rb6" src="https://user-images.githubusercontent.com/47021172/69777021-d493ef00-11e1-11ea-954b-819c7eaf7951.png">

**Comment by birtles** [comment]
Yes, that looks like the same bug.
