### ISSUE TITLE
Idea: occasionally ignore も?

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#169]
I don't know if this is feasible, but it would be nice to see things like わけにもいかない being parsed as わけにはいかない by rikaichamp.

**Comment by birtles** [comment]
I wonder how many cases there are where that would be useful.

Off the top of my head I think of cases like 早くもない but that and 早くはない have a different nuance to 早くない and the existing parsing for those seems reasonable. わけにもいかない gives much less useful information.

**Comment by picsi** [comment]
Yeah, probably not feasible.
