### ISSUE TITLE
Parsing 頑張ろー

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#174]
ー is often used in place of う in colloquial situations. It would be nice if Rikai could detect whether that's happening, and correctly parse that word.

行こー
食べよー

etc

**Comment by birtles** [comment]
Yes, good idea.

**Comment by birtles** [comment]
I thought about this a bit more and I'm not sure how far to take this. It's not just volitional verbs but also things like おはよー and そーゆー (そう言う).

Perhaps we can test for a string that is _not_ katakana but contains ー and then try re-matching with ー substituted as う. That would probably suffice for most cases.

**Comment by picsi** [comment]
Strange bug possibly related to this:

クリスチーナ gets converted to クリスチアナ.

**Comment by birtles** [comment]
Yeah, that looks like a bug here: https://github.com/birtles/rikaichamp/blob/c5d54830e36517236d74cb5aac04d817db4f582c/src/data.ts#L305

(should be い not あ at the end of the substitution)

**Comment by claudiofreitas** [comment]
@birtles Do you mind if I try to fix this one?
This seems like an easy one to get started, if I may. 🙂

**Comment by birtles** [comment]
> @birtles Do you mind if I try to fix this one?
> This seems like an easy one to get started, if I may. 🙂

By all means, please go ahead! Thank you!
