### ISSUE TITLE
Recognize if a suru verb is followed by suru and merge with the verb stem

### ISSUE THREAD

**Issue by Kala-J** [birtles/rikaichamp#180]
Currently if there is a する verb (like 記憶する), する is being parsed separately from the verb stem. Since the dictionary already has information about what words are する verbs [it says (n,**vs**) in the previous example], could you check if such a word is followed by any of the possible する forms and merge it together?

**Comment by birtles** [comment]
Is this suggestion simply about the range of text that is selected?

Obviously the dictionary still only has the noun form, "memory, recollection, remembrance", so even if we select the する part as well, it's not going to be able to show "to remember, to recall" for 記憶する.

**Comment by Kala-J** [comment]
The range of text selected, and also add a conjugation marker like rikaichamp already does for te-form, passive, etc. I was thinking the main purpose being to prevent the する conjugation from being parsed as something else. For example, in the following sentence (from "I Am a Cat").

そこを**我慢して**無理やりに這って行くとようやくの事で何となく人間臭い所へ出た。

The して is first displayed as 仕手, but because it is preceded by a suru verb we should know that it has to be the te form of suru (which shows up as the fourth entry in this example).

My suggestion is to highlight the entire selection and display ( < suru < -te ) to indicate how it is being conjugated.
