### ISSUE TITLE
Selecting Japanese text with the addon enabled is very difficult

### ISSUE THREAD

**Issue by kuchitsu** [birtles/rikaichamp#19]
I find it very difficult to select a specific Japanese text with the addon enabled. Usually I manage to select only the latter half of it, or nothing at all. It seems very chaotic. I can record a video if necessary.

One interesting thing I noticed is that I don't experience any troubles if the said text is followed by a punctuation mark **and** I select it backwards (i.e. by moving the cursor from right to left). But in all other cases I've seen so far something seems to confuse Firefox. I assume it is somehow related to Rikaichamp's parser.

**Comment by birtles** [comment]
Yes, this is a known issue. I need to turn off text highlighting when the mouse is used. This is pretty high on my list of things to fix.
