### ISSUE TITLE
Shortcut customization

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#2]
Having the Enter key as a shortcut is actually a problem when you're typing stuff. It'd be neat if one could choose either Shift, Enter, or both.

**Comment by birtles** [comment]
That's pretty easy to do but wouldn't there be a problem where if you type 'd' or 'j/k' to move the pop up you'd end up toggling definitions or moving the pop up down/up?

I'm trying to understand the interaction here. Is it that you want to have the popup showing while you type?

If that's the case, then maybe we should disable the shortcut keys while the user has focussed on a text input of some sort.

**Comment by picsi** [comment]
>If that's the case, then maybe we should disable the shortcut keys while the user has focussed on a text input of some sort.

Yes! That sounds perfect :)

**Comment by birtles** [comment]
Ok, I'll do that. It might take a day or two though because there's a bit of complex interaction involved where rikaichamp actually changes the focus in order to get the browser to highlight text in text boxes correctly (something rikaikun doesn't do). And there are already a couple of bugs there that I should fix at the same time.

**Comment by birtles** [comment]
I'm not sure where the rikaichan code is but rikaikun only highlight text if you focus the textbox.

**Comment by birtles** [comment]
Should be fixed by 65929bc2a90624ea105c21ef3661c5c7f653fa16 and released in version 0.0.6.

**Comment by nanaya** [comment]
Thanks but it seems to be still in effect in yahoo auctions' search box ( https://auctions.yahoo.co.jp ).

<sub><sub>An option to disable shortcut entirely would be nice. Also to disable highlights.</sub></sub>

**Comment by birtles** [comment]
Oh, so you want to be able to focus on the text box but point to something else and have the keys be ignored? I hadn't thought about that. I'll see what I can do.

If you disable shortcuts entirely how would you cycle through the dictionaries?

**Comment by nanaya** [comment]
now you mention it apparently I only ever need word dictionary (or kanji if no word found).

**Comment by birtles** [comment]
Hi @Bennyhana-chachacha!

I'm sorry for the trouble you're facing! I suspect you may have accidentally changed the setting to hide definitions.

In the options screen you can turn them on or off using "show definitions".

![image](https://user-images.githubusercontent.com/1232595/140233224-ffcb82bc-bd70-478a-a9b5-f24ee4aff9ed.png)

(That option can also be toggled by pressing the <kbd>d</kbd> key while the popup is showing but that key should be disabled by default. Perhaps it is still enabled for users on older versions of the add-on.)

Does that help?

**Comment by Bennyhana-chachacha** [comment]
Oddly the D key doesn’t seem to be working. I’m not sure where to look in the options menu and will surely poke around when I get to a computer (Using Firefox version).

**Comment by birtles** [comment]
> Oddly the D key doesn’t seem to be working. I’m not sure where to look in the options menu and will surely poke around when I get to a computer (Using Firefox version).

Oh, in that case I'm not sure how that setting got flipped, or if that's even the problem.

Just to check, is the problem with the definitions now showing, happening on Firefox on a desktop computer (as opposed to a phone / tablet)?

On a computer you should be able to access the options by right-clicking the 10ten icon and choosing "Manage extension", then going to the "Options" tab:

![image](https://user-images.githubusercontent.com/1232595/140236156-02f3cf7c-8740-43b0-9132-6a42d121b840.png)

**Comment by Bennyhana-chachacha** [comment]
I see. My Mac is oriented differently but I’ll look for the “manage extensions” icon.

**Comment by birtles** [comment]
Oh yes on Mac there should be a setting for that. I think it also shows a context menu from the toolbar icon.

**Comment by Bennyhana-chachacha** [comment]
Still looking! Lol I'll check firefox for where I can find the menu to
modify plugins

**Comment by Bennyhana-chachacha** [comment]
FINALLY fixed it! Thank you. Now I still have no idea why the shortcut
wasn'T working....

**Comment by Bennyhana-chachacha** [comment]
I'm almost positive that the shortcut was clicked but I don't know how to
get it to work again...

**Comment by birtles** [comment]
> FINALLY fixed it! Thank you. Now I still have no idea why the shortcut wasn'T working....

That is great news! Thank you for letting me know!

That shortcut should be disabled by default but if it is enabled, I'm not sure why it wasn't working. One possibility is that it doesn't work if the web page is not in focus.

**Comment by Bennyhana-chachacha** [comment]
I used to have this issue with Rikaichan ALL the time and I'd go nuts. Then
of course Firefox made it such that the plugins wouldn't work if you
updated too "high," so I switched to Rikaichamp. I was still using
Rikaichamp until this week until the "D" key got toggled or something and I
hit D two thousand times and the definitions didn't come back. I then in
turn downloaded 10ten as a result. Not bad so far, will take some getting
used to.

**Comment by birtles** [comment]
> I used to have this issue with Rikaichan ALL the time and I'd go nuts. Then of course Firefox made it such that the plugins wouldn't work if you updated too "high," so I switched to Rikaichamp. I was still using Rikaichamp until this week until the "D" key got toggled or something and I hit D two thousand times and the definitions didn't come back. I then in turn downloaded 10ten as a result. Not bad so far, will take some getting used to.

10ten (aka Rikaichamp) _should_ disable the <kbd>d</kbd> key by default precisely because users would accidentally press it and not know how to get the definitions back.

It's possible that if you have an old installation that key might not be disabled? I'm not sure and I'm not sure why the definitions got toggled.

If it happens again please let me know either by (1) [filing an issue here](https://github.com/birchill/10ten-ja-reader/issues/new/choose), or (2) [starting a discussion](https://github.com/birchill/10ten-ja-reader/discussions/new), or (3) emailing me at info@birchill.co.jp.

I hope you like the changes we've made to 10ten. There are [a lot of new features](https://github.com/birchill/10ten-ja-reader/blob/main/CHANGELOG.md) and improvements and more coming all the time.

**Comment by Bennyhana-chachacha** [comment]
Thank you sir! It looks pretty dope so far. I'm loving the "names" section.
