### ISSUE TITLE
Names dictionary doesn't know how to handle more than one PoS

### ISSUE THREAD

**Issue by nicolasmaia** [birtles/rikaichamp#201]
See for instance マルタ. 

Rikai shows 

> マルタ Malta; (f) Marta; Martha [green icon]

When in fact it should show two icons.

**Comment by birtles** [comment]
This should be fixed in the upcoming 0.2.0 release.

<img width="296" alt="multi-pos-after" src="https://user-images.githubusercontent.com/1232595/92427127-9db62500-f1c6-11ea-94ef-8af27110b342.png">
