### ISSUE TITLE
Idea: convert years automagically

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#202]
It would be nice it Rikai could natively read 昭和56年 and display 1981, for instance. Jisho.org does that: https://jisho.org/search/%E6%98%AD%E5%92%8C56%E5%B9%B4

**Comment by birtles** [comment]
Hopefully this mostly works now. If anyone wants to give it a spin they are welcome to try.

**Comment by picsi** [comment]
Awesome, thanks!

Looking forward to the next release 🙌

**Comment by birtles** [comment]
This has now shipped and should be available in 0.0.17.

**Comment by picsi** [comment]
I love it! Thanks!

**Comment by birtles** [comment]
Thanks for the idea!

**Comment by picsi** [comment]
Interesting quirk in this new feature: 昭和111年 -> 2036年

Probably not a bug that needs fixing per se, but interesting nevertheless.

**Comment by birtles** [comment]
Yes, that's deliberate. Sometimes you encounter content with years that don't technically exist, e.g. 平成32年 because materials were produced before the new era was announced. So Rikaichamp deliberately doesn't know or care about the end of each era and just calculates from the start.
