### ISSUE TITLE
Strange popup behavior on this site

### ISSUE THREAD

**Issue by kuchitsu** [birtles/rikaichamp#21]
I've encountered a site where rikaichamp works in a strange way. Instead of the usual behavior, the popup appears on the bottom of the page with the site's native font and background color.  [Check it out](http://www.rondely.com/esp/first/inv.htm), and here is a [screenshot](https://i.imgur.com/9lNHlve.png) with an example if you need it.

**Comment by Lebon14** [comment]
That's weird. For me, it's worse... I don't see anything.

**Comment by birtles** [comment]
I think there's something going wrong with the encoding used to recognize the stylesheet. My guess is that it's using the page's encoding (UTF16, despite being declared as UTF8) and I probably need to annotate the stylesheet (`@charset "utf-8";`) to force it to be recognized as UTF-8.

**Comment by birtles** [comment]
Fixed by 2ebb9b7fcd8abc51312d874236decfeea11a45ff
