### ISSUE TITLE
Popup no longer works on Excel Online

### ISSUE THREAD

**Issue by FibYar** [birtles/rikaichamp#230]
I have some electronic table in Excel Online (onedrive.live.com). There are a lot of cells with Japanese text (I use Excel Online to translate some stuff). Some months ago I could to move mouse cursor to any cell and get a popup with translation by RikaiChamp. But now there are no more popups (maybe some update from Excel Online?). I can only get translation popups in "formula edit field".

**Comment by birtles** [comment]
I had a look into this and it appears that, at least in Firefox, Excel Online renders the cell contents with `<canvas>` so there's no text there for Rikaichamp to highlight. Unfortunately, I'm not sure what else we can do about this.

Excel does reproduce the text in the highlighted cell as a hidden element for screen readers to pick up, but it only applies to the highlighted cell it seems.

**Comment by birtles** [comment]
I just checked and it's the same in Chrome too. Unless anyone has any good ideas of how to work around this, I think there's nothing we can do here so I'm closing it for now. Please feel free to re-open if you have an idea of how to fix this.
