### ISSUE TITLE
Cannot screenshot words on macOS

### ISSUE THREAD

**Issue by CYBAI** [birtles/rikaichamp#235]
On macOS, hotkey of screenshot is `Cmd + Shift + 3 or 4`.

With rikaichamp, I'm able to search the kanji though, if I'd like to screenshot the words, I will trigger kanji search instead due to `shift`.

STR:

On [nikkei's homepage](https://www.nikkei.com/),

1. Hover to `速報`
2. Wanna screenshot how to pronounce `速報`
3. Use `Cmd + Shift + 4`

#### Expected Result

Able to screenshot the word (`速報` in this case)

#### Actual Result

Kanji search triggered, then can't screenshot `速報`

![Apr-17-2020 12-49-38](https://user-images.githubusercontent.com/6782666/79530319-f6ffa980-80a9-11ea-8af4-af2c068ddca5.gif)

**Comment by birtles** [comment]
I checked the code and it looks like if we get <kbd>Shift</kbd> in combination with something else we [ignore it](https://github.com/birtles/rikaichamp/blob/c5d54830e36517236d74cb5aac04d817db4f582c/src/content.ts#L457-L461) but we don't do the reverse -- skip switching dictionaries if there are other keys pressed at the same time.

**Comment by birtles** [comment]
@CYBAI This should hopefully be fixed when I release the next version. In the meantime, do you know there is the <kbd>c</kbd> shortcut you can use to copy an entry to the clipboard?

**Comment by CYBAI** [comment]
> This should hopefully be fixed when I release the next version.

Thanks!!!

> In the meantime, do you know there is the c shortcut you can use to copy an entry to the clipboard?

ohhh, didn't know that! Thank you for letting me know that tip! :D
