### ISSUE TITLE
not working in dark screen reader view in Firefox 75

### ISSUE THREAD

**Issue by cookieo** [birtles/rikaichamp#236]
Also does not work in light screen, but dark screen reading with rakaichamp is very much desired.

**Comment by birtles** [comment]
Unfortunately Web Extensions can't currently work in reader mode due to [Mozilla bug 1371786](https://bugzilla.mozilla.org/show_bug.cgi?id=1371786).

**Comment by birtles** [comment]
Closing for now. Please re-open if I've misunderstood the bug, however.

Once the issue is resolved in Firefox, Rikaichamp should just work in reader mode.
