### ISSUE TITLE
Definition order is reversed

### ISSUE THREAD

**Issue by j9d3it** [birtles/rikaichamp#26]
The order of definitions (kanji readings) is reversed from other dictionaries based on WWWJDIC (edict2) and other extensions. I hope it'll be an easy fix.

![Example of how it works.](https://user-images.githubusercontent.com/26203575/34861438-20bdc082-f7a8-11e7-94ef-3380fea33761.png)

Somehow it's been displaying the least common reading first. This applies to all words with multiple definitions, not just 画面.

EDIT: It seems like it's a problem with the dictionary file. Would require somehow re-generating the dictionary file to fix. See example below.
![画面 example](https://user-images.githubusercontent.com/26203575/34861765-1499b2d2-f7aa-11e7-9789-0b83d9b3a857.PNG)

![人々 example.](https://user-images.githubusercontent.com/26203575/34861700-adf98106-f7a9-11e7-9a4a-fff9ed12dec1.PNG)

**Comment by birtles** [comment]
Unfortunately the dictionary is currently generated from the edict file which doesn't contain this information (it lists にんにん separately from and before ひとびと). I'm working on an alternative database based on either the edict2 file or JMDict file that should fix this.

**Comment by j9d3it** [comment]
Awesome! Using JMDict may also help with the multiple languages situation as referenced in issue #16.

**Comment by birtles** [comment]
Yeah, good point. I should probably try to cover that at the same time.

**Comment by birtles** [comment]
This should be fixed in the next release.
