### ISSUE TITLE
ダイエット?

### ISSUE THREAD

**Issue by nicolasmaia** [birtles/rikaichamp#264]
I came across this word on Instagram: ダイエット

For some reason the ダ doesn't seem to be exactly the same as ダ. Not sure why or if it needs fixing on Rikai's side.

**Comment by Yay295** [comment]
It looks like a Unicode issue. The first character is actually two glyphs:
U+30BF : KATAKANA LETTER TA
U+3099 : COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK
while the second character is a single glyph:
U+30C0 : KATAKANA LETTER DA

**Comment by birtles** [comment]
Yes, this is hopefully just a matter of converting to normalized form at the point were we do other transformations (like converting half-width katakana). I'll look at this in the next few days.

**Comment by birtles** [comment]
This was a lot more involved than anticipated because Rikaichamp needs not only to normalize, but also recognize what the original character offsets were in the non-normalized form so it can select the text in the original document.

Anyway, it should be fixed in the next release.
