### ISSUE TITLE
Pressing 4 refreshes the page

### ISSUE THREAD

**Issue by mikob** [birtles/rikaichamp#28]
Strange issue I have with this add-on, when I press the numeral "4" on any page it refreshes. Doesn't matter what's in focus it seems -- can even be within a textbox.

**Comment by birtles** [comment]
That's very odd. There's nothing in the add-on that refreshes the page and nothing that listens for 4 key. Are you sure it's this add-on?

**Comment by mikob** [comment]
sorry, I noticed the issue went away when I disabled rikaichamp but now I can't reproduce it. Perhaps it's not with this add-on after all.
