### ISSUE TITLE
Weird word splitting

### ISSUE THREAD

**Issue by SaltfishAmi** [birtles/rikaichamp#286]
![ 昭和三大馬鹿査定」発言にお was recognized as one word and the AD year of 昭和三年 is shown](https://user-images.githubusercontent.com/14184974/83426936-839bd680-a462-11ea-8ba3-ad1894d3d4c1.png)

`昭和三大馬鹿査定」発言にお` was recognized as one word and the gregorian year of 昭和三年 is shown

This issue is not present in Rikaichan, neither does Rikaichan have Japanese calender conversion feature.

For your information, the webpage is Japanese wikipedia "青函トンネル" entry.

**Comment by birtles** [comment]
Thanks! This should be fixed in the next release.
