### ISSUE TITLE
Update jmdict

### ISSUE THREAD

**Issue by krofna** [birtles/rikaichamp#3]
Judging from the fact that it didn't recognize 大州 ([which was added to jmdict in 2011](http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2614490.1)), this addon seems to be using a **really** old copy of jmdict. There were substantial changes to the dictionary in the last 6+ years so users could benefit from an update.

**Comment by birtles** [comment]
Yes, I definitely want to do this. Eventually I want to setup a separate sync for the database so it can be updated frequently by just downloading the changes but that will take a little while so for now I should just do a manual update. I'll see if I can do it in the next few days. I probably need to write a script to regenerate the indices.

**Comment by birtles** [comment]
I still need to update the names and kanji dictionaries, but this is a start.

Longer term I also need to switch to using the edict2 database but hopefully I can tackle that as part of converting to a separate dictionary sync server.
