### ISSUE TITLE
Feature request: combine completely identical entries

### ISSUE THREAD

**Issue by SaltfishAmi** [birtles/rikaichamp#300]
This is the current behavior:
![Untitled1](https://user-images.githubusercontent.com/14184974/84876151-7e24ca00-b0b9-11ea-8609-a0b593483c2a.png)

I think this would be better:
![Untitled2](https://user-images.githubusercontent.com/14184974/84876169-84b34180-b0b9-11ea-993d-53b1ebad2fb6.png)

**Comment by birtles** [comment]
Yes, that's definitely a better view.

(For what it's worth, I'm currently deep in reworking the way the kanji data files are generated. After that's done, I hope I can do the same for the names data--and fix a number of issues in the way we present names. Then finally do the same for the word data. At that point this should be a lot easier to fix.)

**Comment by SaltfishAmi** [comment]
This is already fixed in 0.3.0.
