### ISSUE TITLE
Can't recognize the masu term of irregular verb いらっしゃる

### ISSUE THREAD

**Issue by SaltfishAmi** [birtles/rikaichamp#303]
いらっしゃる and いらっしゃらない can be correctly recognized, but in いらっしゃいます it will only recognize いらっしゃい as "welcome", but not the masu term of いらっしゃる.

The same for 仰（おっしゃ）る and おっしゃいます.

Maybe I'll dig into deinflect.ts and create a pr in a few days, but don't count on me...

**Comment by birtles** [comment]
Yeah, we should do this. I really should just re-write deinflect.js as a separate module anyway and make it easier to maintain. It's pretty horrible the way it's currently set up and I recently regressed it badly.
