### ISSUE TITLE
Stops working randomly

### ISSUE THREAD

**Issue by riesza** [birtles/rikaichamp#31]
Not really sure what causes it but it seems to stop working randomly until I turn it off and then back on again. I've had this for a couple weeks now. Firefox 60.0b4 (64-bit)

**Comment by birtles** [comment]
Thanks for the report. Are you suggesting it only started happening recently? I think I've noticed that too. I wonder if it's related to the changes to Promise handling in Firefox that landed ~2 weeks ago.

Anyway, I'm closing this as a duplicate for #17 for now. I'm reworking the dictionary databases significantly in a way that _might_ fix this. If it doesn't I'll try to investigate more.
