### ISSUE TITLE
feature request: option to disable on specific domains

### ISSUE THREAD

**Issue by majewsky** [birtles/rikaichamp#312]
Rikaichamp is very helpful for reading, but on kanji learning tools like WaniKani, it's an annoyance when I hover over the kanji that I'm supposed to define and the definition pops up by accident. I would like to configure the extension to stay silent on the domain of my learning tool.

**Comment by birtles** [comment]
Hi! Have you tried the "Hold to show popup" setting?

![image](https://user-images.githubusercontent.com/1232595/86184320-e8844280-bb6e-11ea-93f1-95bfcb3e3062.png)

With that you can leave Rikaichamp enabled all the time and just show the pop-up when you need it.

**Comment by majewsky** [comment]
Thanks for pointing that out; I'll give it a try.
