### ISSUE TITLE
Not working in Reader mode

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#32]
I just tried Reader mode at http://www.hachidory.com/food/00/id=758 and it isn't working. When I leave Reader mode, it works normally again.

**Comment by birtles** [comment]
I had a look and it seems like the script / CSS don't get injected in reader mode. Perhaps Web Extensions can't affect reader mode.

**Comment by picsi** [comment]
You may be right about that https://bugzilla.mozilla.org/show_bug.cgi?id=1286387

**Comment by birtles** [comment]
Yeah, this is covered by [bug 1371786](https://bugzilla.mozilla.org/show_bug.cgi?id=1371786) which seems to have stalled. I'm going to close this issue for now although I'm following the Firefox bug so if it makes traction, I'll re-open it.
