### ISSUE TITLE
randomly stops working

### ISSUE THREAD

**Issue by Matsurika** [birtles/rikaichamp#34]
the addon seems to stop working once every so often. im not sure what causes it, but the icon indicates that it's still enabled. only disabling+reenabling the addon (via the icon or addons page) seems to fix the issue (until it happens again)

**Comment by birtles** [comment]
Hi, thanks for reporting! I'm closing this as a dupe of #17 although it definitely seems to be more frequent recently. I wonder if it's related to changes in microtask handling in Firefox.
