### ISSUE TITLE
version 0.1.19 suddenly not working on Firefox 79 MacOS 10.15.6

### ISSUE THREAD

**Issue by cookieo** [birtles/rikaichamp#342]
Hi, I'm pretty sure this was working even after the updates to Firefox and MacOS, until today I noticed it had stopped. It does not work on any webpage it was working on before.

I've tried quitting and restarting Firefox, enabling and disabling Rikaichamp, etc.  

The only thing in the browser console is:
Promise rejected after context unloaded:   rikaichamp-content.js:1415
      ts moz-extension://7ec etc etc etc/rikaichamp-content.js:1415

The other filters - options.js, etc. - return no errors.

**Comment by birtles** [comment]
Thank you so much for filing this. That's really concerning.

Looking at that particular error, I _think_ it means that the background script is failing to load.

Specifically, it appears to be this part here:

```js
// When a page first loads, checks to see if it should enable script
//
// Note that the background script might not have been initialized yet in which
// case this will fail. However, presumably once the background script has
// initialized it will call us if we need to be enabled.
browser.runtime.sendMessage({ type: 'enable?' }).catch(() => {
    /* Ignore */
});
```

I've noticed an uptick in network errors recently too but I'm not sure if it's related.

It's also possible that 0.1.19 just increased the size of the name and word dictionaries just enough that it causes reading to timeout on your computer?

Can I ask what version of Mac OS X you are on? (So I can see what sort of errors are being logged for that platform.)

**Comment by cookieo** [comment]
Yes.  It’s 10.15.6

I have to assume that an update to Firefox or my recent update to 10.5.6 is the cause but I just did not notice the problem. 

Because I’ve been running rikaichamp 0.1.19 for a while. 

Thanks for looking into it.

**Comment by birtles** [comment]
Thank you! Are you using Firefox Nightly by any chance?

I will try to release an updated version of Rikaichamp in the next day or two with some extra logging and error handling that might help.

**Comment by cookieo** [comment]
No, I just update when Firefox notifies me.  

Thanks again.

**Comment by cookieo** [comment]
Hi, I noticed you update to 0.1.20, but unfortunately rikaichamp still is not working. :-(

There are no errors under “Web Developer” —> “Browser Console” when filtering for “rikai”.

**Comment by birtles** [comment]
That's really odd. I wonder if there is some other extension or setting that is interfering (since the error started occurring after updating Firefox / OS X as opposed to rikaichamp).

The other place to check for errors is "about:debugging" → "This Firefox" → "Rikaichamp" → "Inspect". That should show any errors from the background script.

Other than that, the next step is probably to try uninstalling and re-installing Rikaichamp.

**Comment by cookieo** [comment]
Hi, while on the Inspector tab, at the bottom of the page, it says 

Error: Can't find profile directory. 

Hopefully a clue?

**Comment by cookieo** [comment]
Okay, here’s something that suggests the problem is with Firefox/Mozilla.  

To continue using Rikaichamp, the other day I downloaded the previous version of Firefox (78.0.2).

Rikaichamp works fine with this version - the problem is that I have none of my bookmarks.  Anyway …


Just now I confirmed that Rikaichamp still does not work with version 79 - even after uninstalling and reinstalling Rikaichamp at your suggestion.


The odd thing is that it seems that Mozilla automatically updated my 78.0.2 Firefox to version 79 without my noticing  - but the *new* version 79 DOES WORK with Rikaichamp.

So I have a version 79 that does not work, and a version 79 that does work.  

I wouldn’t mind so much except for the fact that they updated the Firefox that HAS NONE OF MY BOOKMARKS OR SETTINGS.  I’m starting with a more or less blank slate.

Anyway, at this point, this is no longer your problem.  I appreciate your looking into it!

**Comment by birtles** [comment]
Thanks for looking into this!

One thing you could try is to "Reset" Firefox.

1. Go to `about:support`
2. Choose `Refresh Firefox...`

This will delete all your cookies (and maybe extensions too?) but it should at least keep your bookmarks. So you could try that on the Firefox version with your bookmarks?

**Comment by cookieo** [comment]
Thanks for the tip.  I’ll try it out
