### ISSUE TITLE
"Update failed: ReadableStream is not defined"

### ISSUE THREAD

**Issue by Yay295** [birtles/rikaichamp#346]
Just putting this here since I already fixed the issue.

I got this error in Waterfox Classic (latest version - 2020.07.2). Apparently this is because [ReadableStream wasn't enabled by default until Firefox 65](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream), and Waterfox Classic is older than that. The code is there though, and it can be enabled in `about:config` by setting `dom.streams.enabled` and `javascript.options.streams` to `true`.

**Comment by birtles** [comment]
The extension manifest for rikaichamp indicates that Firefox 65 is the minimum supported version so I guess Waterfox is failing to respect that.
