### ISSUE TITLE
Won't work with websites.resistFingerprinting enabled

### ISSUE THREAD

**Issue by mrmotallebi** [birtles/rikaichamp#35]
As the title says. This is despite giving canvas access permission to the add-on manifest page.  
Also, even with resistFinerprinting enabled, upon enabling Rikaichamp, it would show the blue box for an instance if the mouse pointer is over a Japanese word but then won't work afterwards.  
Is this fixable, or anything that can be done to fix it?

PS: Nothing is printed in the log.

**Comment by birtles** [comment]
Oh, interesting. I'm not sure what is going on there! Thanks for reporting!

**Comment by Tomalak** [comment]
Almost the same issue here, I have `privacy.resistFingerprinting` on `false`, but I've got an anti-fingerprinting add-on installed ([Canvas Defender](https://addons.mozilla.org/en-US/firefox/addon/no-canvas-fingerprinting/)) and RikaiChamp only works for seconds at a time. No errors in the console.

**Comment by birtles** [comment]
Excellent, thank you! My guess is that d618b0a28caff86d7063589c2a46039cd8e2dfba is to blame because it relies on `performance.now()` which has reduced resolution with `privacy.resistFingerprinting` enabled.

Perhaps we need to check the resolution of `performance.now()` and skip that code path when it's not sufficient.

**Comment by birtles** [comment]
I've checked this fix on two Windows machines, one Mac machine, and a Linux machine and it seems to work as expected on all of them so I'll try to release a new version tomorrow with this fix.

**Comment by birtles** [comment]
I've just released a new version of rikaichamp that includes the fix for this. Please give it a try!

**Comment by FmT0** [comment]
Congratulations ! I can confirm it's working as intended on both macOS and Windows 👍

**Comment by birtles** [comment]
Great, thanks for checking!

**Comment by mrmotallebi** [comment]
Thanks!
