### ISSUE TITLE
Publish in the Chrome and Edge Web Stores

### ISSUE THREAD

**Issue by Brawl345** [birtles/rikaichamp#352]
I'm sideloading this extension in Chrome & Edge but it's kinda annoying having to redownload it and use it through the browser's development mode rather than installing it directly from a Web Store (because you also get a warning after each start). Could you please upload the extension to the Chrome and/or Edge Web Store? (I don't think the CWS needs a fee anymore, but the Edge Store is definitely free). Thanks!

**Comment by birtles** [comment]
Hi! Yes this is on the roadmap for October after I fix #86. Perhaps I can try to shuffle things to do this sooner, though.

**Comment by birtles** [comment]
Chrome Web Store listing: https://chrome.google.com/webstore/detail/pnmaklegiibbioifkmfkgpfnmdehdfan

**Comment by birtles** [comment]
Edge listing: https://microsoftedge.microsoft.com/addons/detail/rikaichamp-japanese-dicti/cgiogkjpebgfcpcaipiicfeaelpapeig

I think that means we can close this issue now.

**Comment by Brawl345** [comment]
Thank you very much!
