### ISSUE TITLE
"potential or passive" is wrong for Godan verbs ending in る

### ISSUE THREAD

**Issue by anonymouse333** [birtles/rikaichamp#36]
I saw this issue reported on Yomichan's GitHub page, and when I tried testing to see whether Rikaichamp was also affected by it, it turned out that it was, so I decided to share the issue here too so as to alert the developer and give him a chance to fix it. The text below is directly copy-pasted from the following page (though with references to "Yomichan" replaced with "Rikaichamp"): https://github.com/FooSoft/yomichan/issues/118

> Ichidan Verbs (correct case):
> Ichidan verbs can be either potential or passive with the られる suffix. This is shown correctly.
> For example: 止められる
> ___
> Godan Verbs ending in る (bug case):
> Godan verbs ending in る conjugate to られる for passive, but they conjugate to れる for potential. This is shown incorrectly as "potential or passive".
> For example: 怒られる
> ___
> There seem to be other similar bugs. For example, Rikaichamp says 起こされる is either "passive or causative", but the causative is 起こさせる (which isn't even detected by Rikaichamp).

**Comment by birtles** [comment]
Thanks for reporting this. This is just a carry-over bug from rikaikun. We should rework that deinflection code, perhaps after fixing the database backend since I suspect we'll need to rewrite this code when that changes anyway.

**Comment by birtles** [comment]
I think all the cases reported in this issue should now be fixed. There are still other inflections that rikaichamp doesn't handle correctly but this should cover these obvious issues.
