### ISSUE TITLE
Ruby text breaks lookups

### ISSUE THREAD

**Issue by anonymouse333** [birtles/rikaichamp#37]
When ruby text is formatted in such a way that the individual characters in a word are separated by <rb> tags, Rikaichamp fails to read the word.

See the following page for some examples:
https://en.wikipedia.org/wiki/Ruby_character#Markup_examples

You will note that when hovering over 東京 (which is formatted as: `<rb>東京</rb>`), Rikaichamp encounters no problems, but when hovering over 振り仮名 (which formatted as: `<rb>振</rb><rb>り</rb><rb>仮</rb><rb>名</rb>`) Rikachamp can't read more than one character in the word at a time.

I don't know how you would go about fixing this. Maybe you could tell Rikaichamp to ignore `<rb>` tags somehow (might be a good idea to make it ignore HTML tags in general actually, since other tags can presumably cause this same breakage). It seems that this problem does not affect Yomichan, so it would appear that it is indeed fixable (maybe you can just copy whatever solution Yomichan's dev came up with).

**Comment by birtles** [comment]
Hi, thanks for reporting this. Yes, this should be fixable. I think it comes about because I made it so rikaichamp could read the ruby text as well (which rikaikun etc. can't). That's probably less important though.

**Comment by birtles** [comment]
In turns out the example on the wikipedia page is a bit misleading. The source it shows is completely different to what is actually used in the markup of the page. In the actual page the markup is:

```html
<ruby><rb>振</rb><rp>(</rp><rt>ふ</rt><rp>)</rp>り</ruby>
<ruby><rb>仮</rb><rp>(</rp><rt>が</rt><rp>)</rp><rb>名</rb><rp>(</rp><rt>な</rt><rp>)</rp></ruby>
```

The bug in rikaichamp is simply that it wouldn't navigate past `<rb>` elements since their computed display is `ruby-base` not `ruby`.
