### ISSUE TITLE
rikai doesn't automatically default to names dictionary sometimes

### ISSUE THREAD

**Issue by nicolasmaia** [birtles/rikaichamp#374]
See, for instance 甚三郎

**Comment by birtles** [comment]
The logic here (which dates back beyond rikaichamp) is to try the three dictionaries in order:

1. Words
2. Kanji
3. Names

(i.e. the same order they are cycled through when pressing <kbd>Shift</kbd> / <kbd>Enter</kbd>)

As a result we never actually default to the names dictionary.

That seems wrong though. We should show a match from the names dictionary first even if we preserve the same cycle order. Thanks for the suggestion!

**Comment by birtles** [comment]
This actually turns out to be more involved since we don't want to default to the names dictionary if the match is just a single character, for example.
