### ISSUE TITLE
Ignore keyboard shortcuts while a textbox is in focus, even if the popup is for a different element

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#4]
As requested by @nanaya in https://github.com/birtles/rikaichamp/issues/2#issuecomment-341158536

**Comment by nanaya** [comment]
Actually in my case, having popup when in text focus usually one of these things:

- accidental mouse movement
- making sure what input I'm typing on by hovering its label (or just figuring out if it's a series of "type and tab" on long forms)
- making sure I remember and use word correctly

And there's actually use case of pressing `j` or `k` even when not in textbox but still don't want to trigger popup shortcut: the page's shortcut itself (navigating between pages etc).

**Comment by birtles** [comment]
The first part sounds like this issue. The second part sounds like adding options to customize/disable certain keyboard shortcuts.

**Comment by birtles** [comment]
Hopefully this is now fixed in the just released 0.0.30.
