### ISSUE TITLE
Update zh-hans translation

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#429]
The next release includes all the word data in structured form which means we can translates the different annotations like part-of-speech labels etc.

I've done a rough job for English and Japanese but the Simplified Chinese keys need updating.

There are a _lot_ of new keys so I made a script to list out the missing ones:

```bash
yarn check-keys -l zh_hans
```

If it's helpful, I also made the script copy all the missing keys from the `en` locale and optionally add a prefix to the message.

e.g.

```bash
yarn check-keys -l zh_hans -c -p "TODO:"
```

**Comment by birtles** [comment]
Note that there will also be at least one more key added since I need to add an attribution for the accent data.

If all this proves too much, we could just copy in the English keys for now, especially for the part-of-speech labels.

e.g.

```bash
yarn check-keys -l zh_hans -c
```

**Comment by SaltfishAmi** [comment]
Sure, I'll look into this.

**Comment by birtles** [comment]
> Sure, I'll look into this.

Thank you so much. I think all the strings have stabilized now and this is the only thing remaining before triggering the next release.

**Comment by birtles** [comment]
This is now done. I will wait until tomorrow morning before triggering the next release, however, in case there are any problems.

**Comment by SaltfishAmi** [comment]
By the way, I copied the keys from the `ja` locale instead of `en`, because there are, obviously, more similarity between Japanese and Chinese and thus saving me from some redundant work.

**Comment by birtles** [comment]
Yes, I noticed that. I think that's a very good idea.
