### ISSUE TITLE
Show all kanji headwords?

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#438]
See discussion in #437 

It might be more useful to show all the kanji headwords, as opposed to just the matching one. We could dim the non-matching ones, perhaps.

I'm concerned this might make things more cluttered but it's still probably worth a try.

**Comment by SaltfishAmi** [comment]
I like this idea very much. But I wonder how many different kanji can match a kana entry at most? We may need a limit.

**Comment by birtles** [comment]
I tried implementing this. How does this look?

![image](https://user-images.githubusercontent.com/1232595/100814436-08ed5b80-3485-11eb-9ef4-8d1703f684dd.png)

**Comment by birtles** [comment]
> But I wonder how many different kanji can match a kana entry at most? We may need a limit.

Good question, I haven't encountered too many yet. Let me check.

**Comment by SaltfishAmi** [comment]
> [image]

How about move the matching one to the beginning?
**路**、道★、途、径 みち★

**Comment by birtles** [comment]
Thanks! I thought about doing that but I assume there is some significance to the order of headwords in JMdict? e.g. common writing first? Maybe it doesn't matter?

**Comment by SaltfishAmi** [comment]
> Thanks! I thought about doing that but I assume there is some significance to the order of headwords in JMdict? e.g. common writing first? Maybe it doesn't matter?

Ah, that’s a very good point.
As a Chinese I have abundant knowledge of kanji already, so it seems difficult for me to think from a kanji learner’s aspect. I may have to reconsider this.

**Comment by birtles** [comment]
It turns out the maximum number of kanji headwords is 12.

```bash
$ cat words.ljson | jq -n "[[inputs][].k | length] | max"
12
```

As for which entries have 12 kanji headwords...

```bash
$ cat words.ljson | jq -n "[inputs] | map(select(.k | length == 12)) | map(.k)"
[
  [
    "一ヶ月",
    "一ヵ月",
    "一カ月",
    "一か月",
    "一箇月",
    "一ケ月",
    "１ヶ月",
    "１ヵ月",
    "１カ月",
    "１か月",
    "１箇月",
    "１ケ月"
  ],
  [
    "一箇所",
    "一カ所",
    "一ヶ所",
    "一か所",
    "一ヵ所",
    "一ケ所",
    "１箇所",
    "１カ所",
    "１ヶ所",
    "１か所",
    "１ヵ所",
    "１ケ所"
  ],
  [
    "磨りガラス",
    "擦りガラス",
    "磨り硝子",
    "磨硝子",
    "擦り硝子",
    "磨ガラス",
    "擦硝子",
    "擦ガラス",
    "摺りガラス",
    "摺ガラス",
    "摺硝子",
    "摺り硝子"
  ],
  [
    "干しぶどう",
    "干しブドウ",
    "干し葡萄",
    "干葡萄",
    "干ぶどう",
    "干ブドウ",
    "乾しぶどう",
    "乾し葡萄",
    "乾しブドウ",
    "乾ぶどう",
    "乾葡萄",
    "乾ブドウ"
  ],
  [
    "二箇年",
    "二カ年",
    "二ヵ年",
    "二ヶ年",
    "二か年",
    "二ケ年",
    "２箇年",
    "２カ年",
    "２ヵ年",
    "２ヶ年",
    "２か年",
    "２ケ年"
  ],
  [
    "三箇年",
    "三カ年",
    "三ヵ年",
    "三ヶ年",
    "三か年",
    "三ケ年",
    "３箇年",
    "３カ年",
    "３ヵ年",
    "３ヶ年",
    "３か年",
    "３ケ年"
  ],
  [
    "四箇年",
    "四カ年",
    "四ヵ年",
    "四ヶ年",
    "四か年",
    "四ケ年",
    "４箇年",
    "４カ年",
    "４ヵ年",
    "４ヶ年",
    "４か年",
    "４ケ年"
  ],
  [
    "五箇年",
    "五カ年",
    "五ヵ年",
    "五ヶ年",
    "五か年",
    "五ケ年",
    "５箇年",
    "５カ年",
    "５ヵ年",
    "５ヶ年",
    "５か年",
    "５ケ年"
  ],
  [
    "六箇年",
    "六カ年",
    "六ヵ年",
    "六ヶ年",
    "六か年",
    "六ケ年",
    "６箇年",
    "６カ年",
    "６ヵ年",
    "６ヶ年",
    "６か年",
    "６ケ年"
  ],
  [
    "七箇年",
    "七カ年",
    "七ヵ年",
    "七ヶ年",
    "七か年",
    "七ケ年",
    "７箇年",
    "７カ年",
    "７ヵ年",
    "７ヶ年",
    "７か年",
    "７ケ年"
  ],
  [
    "八箇年",
    "八カ年",
    "八ヵ年",
    "八ヶ年",
    "八か年",
    "八ケ年",
    "８箇年",
    "８カ年",
    "８ヵ年",
    "８ヶ年",
    "８か年",
    "８ケ年"
  ],
  [
    "九箇年",
    "九カ年",
    "九ヵ年",
    "九ヶ年",
    "九か年",
    "九ケ年",
    "９箇年",
    "９カ年",
    "９ヵ年",
    "９ヶ年",
    "９か年",
    "９ケ年"
  ],
  [
    "十箇年",
    "十カ年",
    "十ヵ年",
    "十ヶ年",
    "十か年",
    "十ケ年",
    "１０箇年",
    "１０カ年",
    "１０ヵ年",
    "１０ヶ年",
    "１０か年",
    "１０ケ年"
  ]
]
```

Which ends up rendering something like:

![image](https://user-images.githubusercontent.com/1232595/100816450-68e60100-3489-11eb-8ca8-c5d70f4fe290.png)

It's not beautiful but it seems ok?

**Comment by SaltfishAmi** [comment]
> [image]

Why is there two `(rare)`s following one headword?

**Comment by birtles** [comment]
Sorting the match(es) first definitely looks better:

![image](https://user-images.githubusercontent.com/1232595/100816840-633ceb00-348a-11eb-8b86-a25964c5f7cc.png)

**Comment by birtles** [comment]
> Why is there two `(rare)`s following one headword?

That headwords has the "ik" (irregular kanji) and "io" (irregular okurigana) annotations and the English localization render `head_info_label_ikanji` and `head_info_label_io` (and `head_info_label_kana`) as "rare".
