### ISSUE TITLE
Disable/enable definition option

### ISSUE THREAD

**Issue by fxmarty** [birtles/rikaichamp#439]
Hello,

There is the possibility with rikaichamp to disable/enable the definition with a shortcut. However after the recent update, I don't have a coherent behavior for this anymore. Meaning, if for example I'm in the mode with definitions disabled, depending on the word I hover on I would sometimes see the definition, sometimes not. Not sure I can better explain it, but I would be happy to provide more details. It's weird because yesterday evening it was working alright.

Edit: Firefox version 78.5.0esr

Thanks!

**Comment by birtles** [comment]
Hi!

Thank you very much for the report!

Oh, that's odd. It's quite possible I broke something there recently. Alternatively, is it just that for some words, Rikaichamp is showing the entries from the names dictionary at the top?

I tried to reproduce the problem but I couldn't yet. If you can send a screenshot with an example of where it is showing the definition when it should not, that would be helpful. Thanks!

Unfortunately I won't be able to look into it properly until Tuesday but thanks in advance!

**Comment by fxmarty** [comment]
Many thanks!

Not sure I could reproduce it consistently, but for example: https://dictionary.goo.ne.jp/en/

With the definition disabled at first:
![Screenshot_20201128_022254](https://user-images.githubusercontent.com/9808326/100491080-48ccdf80-3121-11eb-9f8a-46331d4a0cd5.png)

Press the shortcut to show definition ("d" in my case):
![Screenshot_20201128_022308](https://user-images.githubusercontent.com/9808326/100491074-423e6800-3121-11eb-9ef2-affec76d56a2.png)

Hover over an other word (just below):
![Screenshot_20201128_022324](https://user-images.githubusercontent.com/9808326/100491070-3ce11d80-3121-11eb-9764-535228386310.png)

Hover over every words, the definition do not show.

But I find it to be a bit inconsistent, I do not understand logically what is happening here. Likely the same happens the other way, and when I toggle Rikaichamp (e.g. no definition --> shortcut to show definition --> Toggle OFF rikaichamp --> Toggle ON rikaichamp --> definitions do not show) there are weird behaviors too I feel like.

Many thanks for the addon though, from every day use I see it is getting better and better :)

**Comment by birtles** [comment]
Thank you so much! With those steps I can reproduce it!

I will debug this on Tuesday. Hopefully it will be an easy fix. Thank you again!

**Comment by birtles** [comment]
Ok, this should be fixed in the next release.

For my own reference: we should really drop the `toggleDefinition` message and just send the value we wish to set to the background process.

**Comment by fxmarty** [comment]
Seems fixed indeed! Thank you for the hard work :)
