### ISSUE TITLE
Hardcoded 'or' for multiple probabilities in deinflection

### ISSUE THREAD

**Issue by SaltfishAmi** [birtles/rikaichamp#441]
I noticed that the `or` is not affected by locale.
![Untitled](https://user-images.githubusercontent.com/14184974/100541613-0f5eb600-3280-11eb-8cc0-b45e33431cea.png)

The related code is:
https://github.com/birtles/rikaichamp/blob/8a14de147bb5554e97101e388e7acc2d3535034f/src/data.ts#L234

I guess everyone should be able to understand this simple word, but... _who knows_?

**Comment by birtles** [comment]
This should be fixed by f6ebed044fea95f063160f9b5e241fa701640928 but please check the Chinese (it's entirely based on Google translate).

**Comment by SaltfishAmi** [comment]
> This should be fixed by [f6ebed0](https://github.com/birtles/rikaichamp/commit/f6ebed044fea95f063160f9b5e241fa701640928) but please check the Chinese (it's entirely based on Google translate).

No problem at all!

**Comment by birtles** [comment]
Thanks!
