### ISSUE TITLE
Translate 昭和100年 to both 2025年 and 令和7年

### ISSUE THREAD

**Issue by SaltfishAmi** [birtles/rikaichamp#451]
昭和100年 to `2025年` already works, so this is necessarily translating AD years to the last possible Japanese calendar era, but as long as `const yearMap = new Map<string, EraInfo>` does not support searching by index, I guess implementing this may need some kind of iteration and introduce performance impact. To be honest I'm not familiar with JS performance so I'm not sure how much would it be.

**Comment by birtles** [comment]
We can easily change the data structure (or map it into some sort of reverse-lookup data structure).

Alternatively, we could just get the AD year, subtract 2018 from it, and, if it's positive (and the original date was not already a 令和 date) display it as a 令和 date.

I'm totally happy to hard-code this to 令和. If Rikaichamp is still being used at the next era change I'll be quite happy to update it then!

**Comment by SaltfishAmi** [comment]
I tried implementing this, see: 9b854ed

![Untitled](https://user-images.githubusercontent.com/14184974/101237903-5123ac80-3717-11eb-90d5-1daf4ff819bf.png)

**Comment by birtles** [comment]
Oh I'm sorry, I totally misunderstood the proposal here.

As I believe you know, this is complicated since eras overlap when there were the southern and northern dynasties.

I wonder how important is this feature? That is, how often to invalid years show up where this would clarify things?

As far as I am aware, apart from the occasional reference to 平成31年 (which is probably technically still valid?) I don't think I've ever encountered this.

**Comment by SaltfishAmi** [comment]
> I wonder how important is this feature? That is, how often to invalid years show up where this would clarify things?
> 
> As far as I am aware, apart from the occasional reference to 平成31年 (which is probably technically still valid?) I don't think I've ever encountered this.

Well that's a good question. I think I just considered this as a straight extension to the overflow era year to AD year thing, without thinking about actual usage. Sorry:(

**Comment by birtles** [comment]
> Well that's a good question. I think I just considered this as a straight extension to the overflow era year to AD year thing, without thinking about actual usage. Sorry:(

Not at all! Thank you for all your work on this!

If you don't mind I'd like to close this since I don't think it's worth adding the extra complexity if we agree this is rarely needed.

**Comment by SaltfishAmi** [comment]
Definitely not!
