### ISSUE TITLE
Doesn't work in PDF Files in Firefox 

### ISSUE THREAD

**Issue by MickeyWald** [birtles/rikaichamp#47]
Just a few months ago, pop-up dictionaries like this worked fine in PDF files opened in Firefox. I used Rikaichan this way until the release of Firefox Quantum, switched to Yomichan, and then took a break from Japanese back in late April.

This month, I open a file--and find out Yomichan doesn't work. No problem, I thought, Let's see if the new Rikaichan or Rikaichamp will work. No dice. Every one of them failed.

It seems something that Firefox did in the last few months has made these tools unusable in PDF files, or at least PDF files stored locally on a hard drive. This is a problem, as I have many Japanesepod101 PDF's stored this way, and rely on these tools as a learning aid. 

I'm not especially married to any of these reading aids--in fact, I currently have all three installed, and will use whichever one of them fixes this problem first. Perhaps that will be Rikaichamp?

**Comment by birtles** [comment]
Unfortunately extensions are no longer able to work on pdf.js pages.

There are some details here: https://github.com/birtles/rikaichamp/issues/27#issuecomment-393028168

**Comment by MickeyWald** [comment]
I don't suppose there's an alternate pdf viewer that it does work with?

Or even a tool that displays text from a pdf file as an html document--I'd
swear those things used to exist (heck Google used to convert the $%#@
things all the time, right in the browser), but all I can seem to find is
stuff that only goes the other way.

**Comment by birtles** [comment]
Perhaps you can try uploading to Google Docs/Driver and using the PDF viewer there? Google Docs at least should work.
