### ISSUE TITLE
i18n keys contain characters that Edge disallows (was: Cannot sideload extension in Edge)

### ISSUE THREAD

**Issue by kwilyan** [birtles/rikaichamp#471]
I tried to load latest version in Edge, both on macOS and Windows, dev and current channel build, and it always fail with this notice

ErrorName of a key "misc_label_m-sl" is invalid. Only ASCII [a-z], [A-Z], [0-9] and "_" are allowed.

https://imgur.com/RdH8zmQ

The last version that I can sideload is version 0.2.6.

**Comment by birtles** [comment]
This should be fixed now.

**Comment by birtles** [comment]
I've renamed this and closed it for now. If there are other issues that prevent loading rikaichamp in Edge please file them as separate issues. (For what it's worth I hope to officially support Edge by early next 2021.)
