### ISSUE TITLE
Name dictionary not displaying entries

### ISSUE THREAD

**Issue by Kala-J** [birtles/rikaichamp#478]
Is there something up with the names dictionary? Pressing shift to cycle to it isn't working for many, many names that are present in jmnedict. Just some random examples: 真也、友永、橋本.... For some reason it can find them with hiragana but doesn't seem to have the kanji variants. For example, it can grab はしもと but the list looks a little slim compared to [this.](http://www.edrdg.org/jmdictdb/cgi-bin/srchres.py?s1=1&y1=2&t1=橋本&src=2&search=Search&svc=jmdict)

**Comment by birtles** [comment]
Hmm, it works for me. I wonder if the database index somehow didn't get created?

**Comment by Kala-J** [comment]
![hashimoto](https://user-images.githubusercontent.com/47021172/102177582-39061700-3ee7-11eb-8668-c1bedab24f7c.jpg)

It looks like perhaps just something on my end then...

**Comment by birtles** [comment]
Does it work for _any_ kanji names at all? Or only ever hiragana?

**Comment by Kala-J** [comment]
It works for 羽 (I was trying to see if the "Hashi" from my screenshot worked -- it didn't but the single kanji did), and I tried a bunch of common names but couldn't find any that worked. I did a manual update in the options which downloaded a new dictionary file and didn't change anything.

**Comment by birtles** [comment]
> I did a manual update in the options which downloaded a new dictionary file and didn't change anything.

That's really odd. I don't suppose there are any errors in the browser console? Or if you go to `about:debugging` → This Firefox → Add-ons → Rikaichamp → Inspect?

**Comment by Kala-J** [comment]
Don't see anything in the browser console, but inspecting Rikaichamp shows: DataCloneError: The object could not be cloned. rikaichamp-jpdict.js:4857

Looks like an error while trying to update?

**Comment by SaltfishAmi** [comment]
Is this related to #428  ?

**Comment by birtles** [comment]
Wow, you're too fast! I was just about to post the same comment. `DataCloneError` appears to occur when we hit the quota in some cases. We should probably find a way to detect that and report it correctly.

For @Kala-J's case -- it sounds like there's not enough disk space. See https://github.com/birtles/rikaichamp/issues/428#issuecomment-731920452 which explains why even if you have 1~2Gb free, it might not be enough.

**Comment by Kala-J** [comment]
So it seems, unfortunately this is one of those very cheap laptops with only 32gb and Windows 10 eats it all up. 

It says I have name dictionary 3.0.2 but I guess it got corrupted somehow when the update failed because what I have now isn't working properly.

**Comment by birtles** [comment]
The names dictionary should be 3.0.18 so I guess it fills up the quota after installing only the first two files.

Rikaichamp uses the `unlimitedStorage` permission but perhaps that does not apply because the actual database management happens in a worker and perhaps that permission is not being reflected there?

In any case we should do a better job of reporting errors from this case.

**Comment by birtles** [comment]
> Rikaichamp uses the `unlimitedStorage` permission but perhaps that does not apply because the actual database management happens in a worker and perhaps that permission is not being reflected there?

(Alternatively it could simply be that that permission is not being applied to IDB.)

**Comment by Kala-J** [comment]
I freed up some space and it managed to update to 3.0.6 (still can't find names though) so I guess it wasn't enough! Anyways this is pretty clearly a duplicate of #428 so I'll close it.
