### ISSUE TITLE
Wrong parsing of "ローマじゃない"

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#49]
When parsing ローマじゃないです, Rikaichamp thinks it's looking at ローマ字. This problem can maybe be fixed if you tell the program to never separate じ from ゃ (and other similar cases).

**Comment by birtles** [comment]
That's a good idea!

**Comment by picsi** [comment]
This seems fixed from my end. Did you tweak with it?

**Comment by birtles** [comment]
Oh, no I don't know what happened there. I mean, I half rewrote the de-inflection code so that probably fixed it but actually I didn't expect the behavior to change so I'm afraid I broke other things in the process.

**Comment by birtles** [comment]
`git bisect` says this was fixed by fa1c7f77f826c0342d7aa82da3a230050f67ad2c but I have no idea why.

**Comment by neneko** [comment]
This seems to be broken again.

**Comment by birtles** [comment]
Should be fixed in the next version.
