### ISSUE TITLE
The どく form is not parsed

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#51]
どく, as in で+おく is not parsed. For example, here:

>この本を読んどくと勉強がしやすくなる。

Rikaichamp just gives you the kanji details, but the expected behaviour would be to highlight 読んどく and break it down.

**Comment by birtles** [comment]
Good idea. There are a bunch of contractions that Rikaichamp doesn't handle but that's a particularly bad one since it doesn't even get close!

**Comment by birtles** [comment]
This should be fixed in the next release.
