### ISSUE TITLE
Is request type 'translate' used right now?

### ISSUE THREAD

**Issue by fxmarty** [birtles/rikaichamp#536]
Hello, I dig into the code, and do not manage to trigger this case https://github.com/birtles/rikaichamp/blob/main/src/background.ts#L789 .

Additionally, it seems to me that the function `translate` is not used right now: https://github.com/birtles/rikaichamp/blob/main/src/data.ts#L290

Is my understanding correct?

Thank you!

**Comment by birtles** [comment]
Hi, I'm pretty sure it's used for the alt text on images, text on drop-down list elements etc. You can see the call site here:

https://github.com/birtles/rikaichamp/blob/2811de85996c686bf9444a0e7610aaa6aaf2b55d/src/query.ts#L33

And that's triggered by results from `getTextFromRandomElement`:

https://github.com/birtles/rikaichamp/blob/2811de85996c686bf9444a0e7610aaa6aaf2b55d/src/content.ts#L1139

**Comment by fxmarty** [comment]
Oh I see many thanks, my bad, I did not hover over all the examples.

Most probably I care only about about xsearch request type for my application, I guess at the end of the day the called background methods search/translate amount to the same thing, maybe.

Closing.
