### ISSUE TITLE
Pressing [Enter] to switch dictionaries triggers active links

### ISSUE THREAD

**Issue by Tomalak** [birtles/rikaichamp#54]
If a link is active (i.e. it has the dotted outline, for example by navigating to it with the keyboard, or by clicking on it and returning to the page later), then pressing the [Enter] key while the Rikaichamp popup is open both switches the dictionary (intended) and triggers the link (unintended).

Rikaichamp should prevent the keypress from propagating after handling it, if that's possible.

**Comment by birtles** [comment]
Yeah good point. It looks like we call `preventDefault` for the keydown event, but I guess we might need to call it for the keyup event too.

(In the interim you can always use <kbd>Shift</kbd> to toggle.)

**Comment by birtles** [comment]
I tried to reproduce this on Linux but couldn't. Even after making the link active, if the popup is showing and I press <kbd>Enter</kbd> the link is not followed (but is if the popup is not showing). I tried on Linux using 64 Nightly and 62 Release.

What platform are you on?

**Comment by Tomalak** [comment]
I'm on Windows and Firefox 62.0 (64-bit). 

I could just trigger it with https://weather.goo.ne.jp/. Load page, press tab a few times (link outlines are suppressed in the CSS, but the status line shows the active link), hover any word, press <kbd>Enter</kbd> while the popup is visible. Reliably triggers the active link.

**Comment by birtles** [comment]
Thanks for the STR. I tried to reproduce this on Firefox 62 and Firefox 64 on Linux, and Firefox 62 on Windows but couldn't.

Could you provide more detailed steps to reproduce?

* Which link exactly is highlighted (i.e. what is the URL in the status line)?
* Is Rikaichamp configured to always show the pop-up or just when you could a key?
* Is Rikaichamp enabled when you open the page?
* Which word are you highlighting?

There is analytics code on that page that is watching click events but it also appears to be respecting the `defaultPrevented` state of events and hence ignoring the <kbd>Enter</kbd> events. My only guesses at this point is that some links have extra event handlers that ignore that or you have another add-on installed that is interfering.

In either case calling `stopPropagation` might work but I'd like to be able to reproduce the problem first so I can confirm.

**Comment by Tomalak** [comment]
Yeah, Rikaichamp is enabled when I open the page and popups are configured to be shown automatically. 

Maybe let's try that again on a less crowded page. 

1. Open [https://jisho.org/search/リンク](https://jisho.org/search/%E3%83%AA%E3%83%B3%E3%82%AF)
1. Tab to the highlighted link (red outline in the screenshot below)
1. Hover any non-linked Japanese word - note how the active link is shown in the status line simultaneously with the Rikaichamp popup
1. press <kbd>Enter</kbd>
1. The page loads [https://jisho.org/word/リンク切れ](https://jisho.org/word/%E3%83%AA%E3%83%B3%E3%82%AF%E5%88%87%E3%82%8C)

![FireFox 62 Screenshot](https://user-images.githubusercontent.com/28300/45965250-48f46080-c028-11e8-9563-7524b7c05a81.png)

Behavior is reproducible for me with FF 62 on two separate machines (Win7 and Win10)

**Comment by Tomalak** [comment]
Okay, starting with a blank profile and installing Rikaichamp as the only add-on, I cannot reproduce it either.

I'll try to pin down the interfering add-on and will report back.

**Comment by birtles** [comment]
Thank you! The other possibility is some preference, perhaps even something like enabling Content Blocking (although I think I tried that already).

If after disabling all add-ons other than Rikaichamp it still reproduces then I suppose it could be a preference setting. `about:support` should give a summary of significant changed preferences but it doesn't include everything unfortunately.

**Comment by Tomalak** [comment]
FYI, I'm on vacation. Expect some delay. :)

**Comment by birtles** [comment]
Thanks for letting me know! Enjoy your vacation!

**Comment by birtles** [comment]
@Tomalak Did you have a chance to look at this?

**Comment by Tomalak** [comment]
Oh snap, this completely fell off my radar, ごめん! I'll get back to this within the next week.

**Comment by Tomalak** [comment]
@birtles Okay, I tried to reproduce this behavior with the current version (0.0.28) and sure enough it's no longer happening. I had disabled <kbd>Enter</kbd> as a trigger key, and I've gotten used to it.

If you've changed something, well, then that fixed it. If you haven't, them whichever other extension caused this has updated. In any case, thank you!
