### ISSUE TITLE
Better popup visibility in dark mode

### ISSUE THREAD

**Issue by Tomalak** [birtles/rikaichamp#577]
In a dark mode setting, the boundaries of the popup are awfully hard to make out.

Example from Twitter, especially how the popup basically merges with the next tweet.

![image](https://user-images.githubusercontent.com/28300/115665342-75d59500-a343-11eb-86f6-b02f47cd3db4.png)

It might help to add a discreetly colored border around the popup.

**Comment by birtles** [comment]
I've added a thin border as suggested. I'll wait for a few more fixes to accumulate before making the next release though.

**Comment by Tomalak** [comment]
A white transparent shadow might also do the trick, but the light scheme would need a shadow then, too. Hm...
