### ISSUE TITLE
Don't deinflect って/った to く

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#58]
See: https://twitter.com/Random832/status/1051205809399566336

This appears to be a bug dating back to rikaikun days. Or at least I can't think of any case where that deinflection makes sense.

**Comment by ispedals** [comment]
The rule to deinflect って/った to く is necessary to support 行って／行った to 行く, right?

**Comment by birtles** [comment]
Yeah, good point! I wonder if we should make the rule only match いって、いった then.

There are a few other irregular verbs which we could consider adding too:
https://en.wikipedia.org/wiki/Japanese_irregular_verbs#Euphony

**Comment by birtles** [comment]
This should be fixed now. I added support for a bunch of irregular verbs and also made it so looking up Yodan verbs works too (e.g. のたもうた → のたまう).
