### ISSUE TITLE
Parse 取り除かれ

### ISSUE THREAD

**Issue by TinyMarshmallow** [birtles/rikaichamp#583]
取り除かれ (とりのぞかれ), which appears to be from 取り除く.

Encountered in this sentence: `門のところにあった傾いた鉄柵は取り除かれ、庭にあった紫色の毒の沼地は綺麗な水が流れる噴水と化している。`

**Comment by SaltfishAmi** [comment]
#469

**Comment by TinyMarshmallow** [comment]
Closing due to being a duplicate of #469
