### ISSUE TITLE
Rikaichamp doesn't work with documents loaded via iframe's srcdoc

### ISSUE THREAD

**Issue by TinyMarshmallow** [birtles/rikaichamp#584]
Discovered this bug while trying to read books on Calibre's content server, which uses an iframe with a document inside srcdoc to display the book contents.

Example HTML that reproduces the problem:
```html
<!DOCTYPE html>
<html lang="ja">
        <body>
                こんにちは
                <iframe srcdoc="<html><body>こんにちは</body></html>"></iframe>
        </body>
</html>
```

Rikaichamp correctly recognises the first こんにちは, but will not work on the second.

Loosely related to #13 due to iframe support being broken.

**Comment by TinyMarshmallow** [comment]
I tested the same iframe with Yomichan and it seems to work fine (with the usual caveat of it being squished inside the iframe from #13), so it does seem to be possible to work inside srcdoc, but rikaikun/rikaichamp are doing something different.

**Comment by birtles** [comment]
Thanks! This should be fixed in the next release.
