### ISSUE TITLE
Build from source package fails inside a directory tracked by git due to Husky postinstall hook

### ISSUE THREAD

**Issue by cameel** [birtles/rikaichamp#599]
I wanted to create a rikaichamp build script for Arch Linux User Repository ([firefox-extension-rikaichamp](https://aur.archlinux.org/packages/firefox-extension-rikaichamp/)) and ran into a problem building from a source package provided on the release page. `package.json` in the source package has a postinstall hook that requires a `.git/` subdirectory to either not exist or be in the same directory as `package.json`. This is a problem in the common situation where the build script itself is versioned in git repository and at runtime downloads+unpacks the project tarball into its own directory. This results in an error like this when the hook runs:
```
$ husky install
/tmp/firefox-extension-rikaichamp/src/rikaichamp-0.5.5/node_modules/husky/lib/index.js:20
        throw new Error(`.git can't be found (see ${url})`);
        ^

Error: .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
```

The workaround I found is to pass `--ignore-scripts` option to `yarn install` to skip the hook. This feels like a hack though. It will indiscriminately skip all actions you might want to add to the hook in the future.

I think that `husky install` should be removed from the hook and instead have its own action.

**Comment by birtles** [comment]
Hi!

Thank you for reporting this. I'm afraid I won't have a chance to look into it until tomorrow, however. I believe husky advocates using `pinst` in some situations to skip the install step, but I believe that's more for package installs. I wonder how we should distinguish between "Installing because I want to hack on this package" (in which case I want the husky hooks set up) and "Installing just to build the package".

**Comment by cameel** [comment]
Thanks. No pressure, take your time, this is not very urgent since I have a workaround, just would be nice to get it ironed out eventually :)

Yeah, `pinst` won't help since I'm not doing a production install. I already tried `yarn install --production` but looks I do need dev dependencies to build the package (which makes sense).

Personally, I'd probably just create a separate command for installing husky only on demand. But if you really want to have it in `postinstall` so that it runs automatically, maybe doing something similar to what is suggested in [Disable husky in CI/Docker](https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker) would be an option?

```json
// package.json
{
  "scripts": {
    "prepare": "is-ci || husky install"
  }
}
```

Instead of `is-ci` it could have with a check for an env variable like `RIKAICHAMP_RELEASE=1` or even just `HUSKY=0`.

**Comment by birtles** [comment]
Ok I've added the conditional install for husky now in 925801766ce99c9c3cff2a666391f6d2bab19105.

I'll likely update the setup sometime to use `per-env` to target the different browsers but hopefully it works for now?

**Comment by birtles** [comment]
(And I realized the instructions I added to the README in that commit make no sense at all so I've updated them in a21659b5d7f10e6b6637bb60ab8c89e3bbd8b6ca.)

**Comment by cameel** [comment]
I just checked it locally and it works. Great!

**Comment by birtles** [comment]
Great, thank you!
