### ISSUE TITLE
Add an option to disable all (or just some?) keyboard shortcuts

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#6]
Initially disabling all would probably solve the immediate request but it might be useful to be able to selectively disable / re-configure individual shortcuts eventually. I'm wary of adding too many options, however (but fortunately they _should_ synchronize between different computers).

**Comment by nanaya** [comment]
At least for disabling all it seems like adding a config check and return in onKeyDown is sufficient? (same for highlight with highlightText)

**Comment by birtles** [comment]
Fixed by 151d3573a718e8623000be21b6aac8e010beeb89 (and d0a1e579564bb0e3918f538463eb6e5f9c47202d).

**Comment by nanaya** [comment]
Thanks 👍
