### ISSUE TITLE
Bug: does not work for FIRST CHARACTER OF inputs and textareas in Google Chrome 

### ISSUE THREAD

**Issue by emerencia** [birtles/rikaichamp#605]
Hi Brian,

Thanks for fixing the bug #86 that it wouldn't work at all for inputs and textareas in Google Chrome. It now works for everything except the first character in an input field or text area.

Here is a demonstration of the bug that is easily reproducible: https://streamable.com/3h60n6

You can see here that when I hover over the "日" part of "日本語", it doesn't bring up rikaichamp. And this seems to be because "日" is the first character in the field. When I add a space of period or other character before it, then it works for the whole word.

I tested this also with text inputs and it's the same error (first character doesn't work).

Regular text on a web page does work (i.e., anything that is not in input fields or textareas).

**Comment by birtles** [comment]
Thanks for an excellent bug report! This should be fixed in the next release.

**Comment by birtles** [comment]
Version 0.5.7 has been updated on the Chrome Web Store which should include this fix.
