### ISSUE TITLE
Request: Rikaichamp for Thunderbird 78+

### ISSUE THREAD

**Issue by Lebon14** [birtles/rikaichamp#626]
Hi. I have nothing but good thing about this extension. It's been working flawlessly for... huh... forever now!

However, if I receive an email in Thunderbird that's in Japanese and I want to get a quick understanding what it's about, I can't unless I translate. That's what I love Rikaichamp for: I get to learn Japanese very slowly, keep my hiragana/katakana reading up and what not.

Name suggestion: torichamp (鳥 tori bird)

Cheers!

**Comment by birtles** [comment]
Thanks for your very encouraging message! I had a quick look at the current state of Thunderbird Web Extension support and so far it looks promising. I'm going to try and make time for this in the coming weeks.

For now I hope you don't mind if I duplicate this to issue #46.

Thanks for the name suggestion too! I like it. However, I'm actually considering rebranding 10ten to something else (much less exciting) anyway so I'll probably wait until that's done.
