### ISSUE TITLE
Make the display of name entries more user-friendly

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#64]
They currently contain things like "(f)" and "(s)" and I can never remember what they mean. We can do better. We could probably do something similar for the "(P)" entries in word entries too.

**Comment by picsi** [comment]
I also have no idea what (uk) means, or what the verb acronyms are.

**Comment by birtles** [comment]
I started working on the name handling in the [format-names](https://github.com/birtles/rikaichamp/tree/format-names) branch. Still to do:

- [ ] Add localization data for the various tags
- [ ] Output the markup for the various tags (probably at the end of the line)
- [ ] CSS styling for the tags (including appropriate colours for each theme)
- [ ] When copying to the clipboard, re-serialize the tags as appropriate

**Comment by birtles** [comment]
Alright, this seems to be done now:

![Screenshot](https://user-images.githubusercontent.com/1232595/50555376-a9252d80-0d0e-11e9-87e4-74fdcac09a51.png)

And in a localized build:

![Screenshot JA](https://user-images.githubusercontent.com/1232595/50555381-be01c100-0d0e-11e9-9b53-5cb77ab221ca.png)

**Comment by picsi** [comment]
Looks great!

**Comment by birtles** [comment]
Thanks! I'd like to do something similar for the word lookup but it might require switching database sources first since I think it's not always possible to reliably separate the definitions using EDICT.
