### ISSUE TITLE
request: Better compatibility with renshuu.org

### ISSUE THREAD

**Issue by MarcusAseth** [birtles/rikaichamp#67]
renshuu.org is a SRS quizzing site by many thought as superior to Anki.

On Chrome browser using rikaikun or yomichan they are capable of properly highlight words on renshuu, as shown in the image below:
![immagine](https://user-images.githubusercontent.com/29839218/49489562-e3a0c500-f84b-11e8-9993-6394460e746a.png)

On Firefox using rikaichamp however, words aren't properly highlighted, image below:
![immagine](https://user-images.githubusercontent.com/29839218/49489598-1f3b8f00-f84c-11e8-9034-9e7498697456.png)

All the kanji are analized separately.  Would be possible to make rikaichamp work as well as rikaikun and yomichan when used on renshuu.org?

**Comment by birtles** [comment]
It looks like this site uses content like the following:

```html
<div class="fleft" style="padding-left: ">
  <ruby class="k10">
    <rb>
      <span class="klook">引</span>
    </rb>
    <rt>ひ</rt>
  </ruby>
  <ruby class="k10">
    <rb>く</rb>
    <rt>&nbsp;</rt>
  </ruby>
  <div class="ib little" style="vertical-align: bottom"><svg>...</svg></div>
</div>
```

But it seems like the site is doing its own faux-ruby layout with rules like:

```css
/* ルビベース */
ruby > rb, ruby > rbc
{
    display: table-row-group;
    line-height: 120%; /* 120% */
}
```

Which means that rikaichamp fails to detect the `<rb>` element as a inline element when it does [this check](https://github.com/birtles/rikaichamp/blob/252c2faf942765e4053b23f4c3104ae9b00163b1/src/content.ts#L861-L865):

```typescript
const isInline = (element: Element | null) =>
  element &&
  ['inline', 'ruby', 'ruby-base', 'ruby-text'].includes(
    getComputedStyle(element).display!
);
```

We might need to add specific faux-ruby handling that treats `<rb>` / `<ruby>` etc. as inline elements regardless of their computed style.

**Comment by birtles** [comment]
Thanks for the report by the way. Very helpful.

**Comment by birtles** [comment]
I've tested this and the next version of Rikaichamp, when released, should work correctly with renshuu.org. Thanks for the report!
