### ISSUE TITLE
Update names and kanji dictionaries

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#7]

**Comment by picsi** [comment]
It would be nice to have a script that does this in a regular basis.

**Comment by melink14** [comment]
I guess there's two levels of that.

1. Create an automated update and deploy script that would allow updating the dictionaries offline and then pushing a new version of the extension.

2. Figuring out a way to do online dictionary updates that pull the new dictionary files and then process them in the user's browser. This may be possible but given the heaviness of the processing may be too much for users to make it automatic.

**Comment by birtles** [comment]
I'm working on something pretty ambitious for this. If it works out it should allow daily incremental updates of all three dictionaries (i.e. a few kb each), multiple languages, better lookup times etc.

**Comment by birtles** [comment]
The kanji part is fixed in 22acff056b1d7c3cea4d720cbbfde02d6e60900e so marking this as resolved for now. This will be released in 0.0.20.

I'm still working on the incremental update approach but that's a separate issue.
