### ISSUE TITLE
Request: Order results by word frequency

### ISSUE THREAD

**Issue by MarcusAseth** [birtles/rikaichamp#70]
This is a feature I've saw used in Zkanji (free software dictionary), therefore somewhere there is an open-source database that contains words frequency.
As you can see in the image below, the icon to the left of words in zkanji show the word frequency (detailed number by hovering the mouse on it) with the ones with yellow icon being the most frequent for せんしゅ, as one would expect.
In rikaichamp 選手 doesn't appear in the pop-up because it must be really down below.
So would be cool to have the resoult sorted by frequency of usage :)
![immagine](https://user-images.githubusercontent.com/29839218/49963131-6f36e780-ff17-11e8-81c2-42e983f13af9.png)

**Comment by birtles** [comment]
Oh, that's definitely a bug in Rikaichamp. We do sort by frequency (only roughly currently, but I hope to improve it in the future). However, it looks like we trim before sorting (instead of sorting, then trimming). Thanks for the report!
