### ISSUE TITLE
Deinflection - recognize continuous form

### ISSUE THREAD

**Issue by Tomalak** [birtles/rikaichamp#73]
Wouldn't it make sense to also consider the -te-iru ending deinflection, e.g.

 - 戻っている &rarr; もどる (< -te, < -continuous)
 - 戻っていた &rarr; もどる (< -te, < -continuous, < -past)

Currently the te-iru is not being highlighted at all, which leaves out of the visual clue a stray suffix that actually belongs to the verb:

![current highlighting of continuous verbs](https://user-images.githubusercontent.com/28300/51458876-f9fcd480-1d56-11e9-889d-de3ed5c9c301.png)

**Comment by birtles** [comment]
Yeah, it's a good idea. I've thought about doing it but I seem to recall there being some complications last time I looked into it. It's fairly low priority for me at the moment but I'd gladly take a pull request for it.

**Comment by Kala-J** [comment]
This actually is a lot worse with something like する+ている (ex: 記憶している), because it doesn't even recognize する at all and parses してい as a different word.

**Comment by birtles** [comment]
I think it does actually recognize する in している, it's just that there are so many matches for してい first that it gets truncated. Adding support for している would fix it since it is longer and would appear before matches for してい.

**Comment by Tomalak** [comment]
@birtles Nice, thank you very much! I've looked at this initially but quickly realized that I really don't understand your code well enough to confidently make that kind of change. Looking at your commit now, I think I was right.

**Comment by birtles** [comment]
Yeah, that code is pretty old. I've rewritten about most of it to be more maintainable, but I still need to mess with spreadsheets and things to work out the numbers each time I touch it.
