### ISSUE TITLE
[Question] Similar thing for outside the browser?

### ISSUE THREAD

**Issue by DesolatePsyche** [birtles/rikaichamp#80]
Hello, I'm loving this addon. I just have a question if there is same/similar thing that would work anywhere? On desktop, other software and so on? (I.E I read manga on honeyview  usually and if this sort of addon would work there It would enhance my RAW manga reading and learning reading in Japanese a lot.)

**Comment by birtles** [comment]
Thanks!
I hope to eventually get this to work with Thunderbird (and Chrome/Edge too).

I believe there is a similar tool for Android. And if you have a recent Kindle, you can long-press a word to look it up. (Or at least it works on my one but I bought it through amazon.co.jp so it might be the Japanese model, I'm not sure.)
