### ISSUE TITLE
Rikaichamp can't parse キムチ

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#84]
Not sure why, but キムチ can't be parsed, despite being in the dictionary: http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=1145393

**Comment by birtles** [comment]
Oh nice find. I think this is due to the index being generated incorrectly. It's not normalizing the secondary reading entry.

**Comment by birtles** [comment]
This should be fixed in the next release. Thanks as always for a very helpful bug report.

**Comment by picsi** [comment]
Always happy to help this lifesaving add-on!
