### ISSUE TITLE
Rikai can't parse 予断を許さない

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#87]
Despite it being in the dictionary: https://jisho.org/search/%E4%BA%88%E6%96%AD%E3%82%92%E8%A8%B1%E3%81%95%E3%81%AA%E3%81%84

**Comment by birtles** [comment]
It was only added very recently: https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2838783

It will be supported once I next update Rikaichamp. (I'm still working on automatic dictionary updates.)
