### ISSUE TITLE
Dictionnary update: era names

### ISSUE THREAD

**Issue by Lebon14** [birtles/rikaichamp#89]
Hello!

As you may or may not know, the new Japanese era was officially announced yesterday/today in Japan: 令和 (れいわ). It will start on May 1st 2019. Heisei (平成) will, obviously, end on April 30th.

See this wikipedia page: https://en.wikipedia.org/wiki/List_of_Japanese_era_names

When hovering all the era names, rikaichamp gives the same information as the wikipedia page along with the readings. I think it should be updated will the new info.

Thanks!

**Comment by birtles** [comment]
Yep, I'm aware of it. The entry still hasn't been added to EDICT however ([submitted here](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=2002812)). As soon as it gets added there, I'll update rikaichamp.

**Comment by birtles** [comment]
Fixed by 99d16f7f18d86eb4061fe969f091ba0d059e91ba
