### ISSUE TITLE
Rikai can't parse 蝃蝀 

### ISSUE THREAD

**Issue by nicolasmaia** [birtles/rikaichamp#91]
It might have something to do with the obscurity of the kanji

See https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=2000725

**Comment by birtles** [comment]
It looks like it has to do with that being in JMdict but not EDICT. That should be fixed when rikaichamp switches to JMdict (should happen in July, I expect).

**Comment by birtles** [comment]
That is, if I download `http://ftp.monash.edu/pub/nihongo/edict.gz` and dig into it, it has only the following entry:

```
ていとう /(n) (obsc) (arch) rainbow/
```

**Comment by picsi** [comment]
Was that an oversight of the folks running JMdict?

**Comment by birtles** [comment]
No idea. There's a bunch of information that gets dropped when generating the edict format (e.g. non-English glosses) so it might be intentional.

**Comment by picsi** [comment]
Is this the same reason the addon can't read the kanji 𠏹 in 𠏹沢?

**Comment by siikamiika** [comment]
@picsi 
The dictionary is distributed in three different formats: EDICT, EDICT2 and JMdict. In addition to differences in their structure, they use different character sets and encodings.

- EDICT: JIS X 0208 inside EUC-JP
- EDICT2: JIS X 0208 and JIS X 0212 inside EUC-JP
- JMdict: Unicode inside UTF-8

Rikaichamp uses EDICT, and JIS X 0208 doesn't include 蝃 or 蝀.

𠏹沢 would be supported by both JIS X 0212 and Unicode, but it doesn't have an entry in the dictionary.

http://www.edrdg.org/jmdict/edict_doc.html

**Comment by birtles** [comment]
For what it's worth, as of version 0.1.2 Rikaichamp now uses the original kanjidic UTF-8 sources (along with quite a number of other source data files) and hence can recognize the kanji for 蝃蝀.

I'll work on switching to JMdict sources for the word dictionary next but it will take a few more weeks.

**Comment by picsi** [comment]
@siikamiika 𠏹沢 is actually in JMnedict, but I don't know if that is distributed inside JMdict.

See https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=5005893.2

**Comment by siikamiika** [comment]
@picsi 
ENAMDICT/JMnedict is a different dictionary, but ENAMDICT seems to be bundled with Rikaichamp too: https://raw.githubusercontent.com/birtles/rikaichamp/master/data/names.dat (**warning; 30 MB file**)

𠏹 won't be included in ENAMDICT for the same reasons as 蝃 and 蝀 won't be in EDICT.

```
> rg ほとけ沢
enamdict
5997:ほとけ沢 [ほとけさわ] /(p) Hotokesawa/

JMnedict.xml
68205:<keb>ほとけ沢</keb>

> rg 𠏹沢
JMnedict.xml
68208:<keb>𠏹沢</keb>
```

In addition, 𠏹 is represented using surrogate pairs in Javascript due to its high code point in Unicode, so it will require special handling with length checks. Here are a few workarounds:

```javascript
const text = '𠏹';

// bad
text.length
2
// good
Array.from(text).length
1

// bad
for (let i = 0; i < text.length; i++) { console.log(text[i], i); }
� 0
� 1
// good
for (const c of text) { console.log(c); }
𠏹

// bad
text.charCodeAt(0)
55360
// good
text.codePointAt(0)
132089
```

https://www.edrdg.org/enamdict/enamdict_doc.html

**Comment by birtles** [comment]
I'm working on switching the name dictionary sources over too, but it's currently blocked on getting the new IndexedDB-based setup to work while Firefox is in "Always on Private Browsing" mode (#148), which is going to be a bit of work.

**Comment by smarter** [comment]
印鑑 is also not recognized by rikaichamp but recognized by jisho.org which lists jmdict as a source: http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=15829

**Comment by birtles** [comment]
Thank you for the report! That's very odd. I will look into it on Tuesday.

**Comment by SaltfishAmi** [comment]
> 
> 
> 印鑑 is also not recognized by rikaichamp but recognized by jisho.org which lists jmdict as a source: http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=15829

When I hover on the kana "いんかん", there is no corresponding kanji entry written as 印鑑 appearing in the popup.

**Comment by birtles** [comment]
> When I hover on the kana "いんかん", there is no corresponding kanji entry written as 印鑑 appearing in the popup.

Yes, it's not in the rikaichamp database at all. Nor is 印鑑証明. However 印鑑レス is, which is odd. There seems to be a bug in the job that runs to extract the JMdict data and merge it with other data (like pitch accent data). I'll look into it tomorrow or Tuesday.

**Comment by birtles** [comment]
Got a bit nerd-sniped on this. Turns out 印鑑 is in the rikaichamp upstream database so the bug must be in the step where we generate the JSON diffs. 𠏹沢 is also in the upstream database but is also possibly not being exported correctly.

On the upside, Rikaichamp now correctly recognizes 蝃蝀 so we can close this issue once I work out what is going on with 印鑑 etc..

**Comment by birtles** [comment]
I dug into this a bit further today and it seems like there is at least one gap in the set of records we export. It might be something to do with the way I was using DynamoDB (perhaps even an eventual consistency issue?). This will take a bit of time to debug.

**Comment by birtles** [comment]
I've made a bunch of changes that should address all the cases in this issue. In particular, the next release of Rikaichamp should recognize:

* 印鑑
* 𠏹沢
* 𠏹

Furthermore, it should show the name preview for ほとけ沢.

**Comment by Kala-J** [comment]
逸材 is not recognized either, even though it is in EDICT. Is this something similar?

**Comment by birtles** [comment]
> 逸材 is not recognized either, even though it is in EDICT. Is this something similar?

Works for me. Are you on 0.3.2?

![image](https://user-images.githubusercontent.com/1232595/100974576-da07e000-357f-11eb-8252-77e27c89e645.png)

**Comment by birtles** [comment]
Looks like 逸材 was one of the words that was missing but was re-added in 7a0121dbb4993bea69de9feb825ddb0b681faf97

**Comment by nicolasmaia** [comment]
Not working for 𡱖

**Comment by birtles** [comment]
> Not working for 𡱖

Yeah, it looks like I messed up the range for CJK Unified Ideographs Extension B. It should include this.
