### ISSUE TITLE
Firefox does no longer allow for unsigned extensions

### ISSUE THREAD

**Issue by leu14** [birtles/rikaichamp#95]
So Rikaichamp was auto-disabled as of today (5th May, 2019): Firefox 66.0.3, 64-bit.

Please provide a signed version of the software, so that I can use it again.

**Comment by birtles** [comment]
I'm afraid all add-ons, not just rikaichamp, have been affected by a problem affecting all versions of Firefox. The add-ons team have deployed a fix that works for most people but not all. They are working hard on a more permanent solution.

You can see [this blog](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/) or follow [@mozamo](https://twitter.com/mozamo) on twitter for more recent updates.
